import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, Area, AreaChart, Legend, } from 'recharts';
import { motion } from 'framer-motion';
const CustomTooltip = ({ active, payload, label }) => {
    if (!active || !payload?.length)
        return null;
    return (_jsxs("div", { className: "bg-white rounded-2xl shadow-lg border border-amber-100 p-3 text-sm", children: [_jsxs("p", { className: "font-bold text-stone-700 mb-1", children: ["Session ", label] }), payload.map((entry, i) => (_jsxs("p", { style: { color: entry.color }, className: "font-medium", children: [entry.name, ": ", entry.value?.toFixed(1)] }, i)))] }));
};
export default function StressTrajectoryChart({ data, showCognitive = true }) {
    if (!data || data.length === 0) {
        return (_jsx("div", { className: "flex items-center justify-center h-40 text-stone-400 text-sm", children: "No session data yet. Play some games to see your trend!" }));
    }
    return (_jsx(motion.div, { initial: { opacity: 0, y: 16 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2, duration: 0.5 }, className: "w-full", children: _jsx(ResponsiveContainer, { width: "100%", height: 220, children: _jsxs(AreaChart, { data: data, margin: { top: 10, right: 10, left: -20, bottom: 0 }, children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "stressGrad", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#f59e0b", stopOpacity: 0.25 }), _jsx("stop", { offset: "95%", stopColor: "#f59e0b", stopOpacity: 0.02 })] }), _jsxs("linearGradient", { id: "cogGrad", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#10b981", stopOpacity: 0.2 }), _jsx("stop", { offset: "95%", stopColor: "#10b981", stopOpacity: 0.02 })] })] }), _jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#fde68a", vertical: false }), _jsx(XAxis, { dataKey: "session", tick: { fill: '#78716c', fontSize: 11 }, axisLine: false, tickLine: false, label: { value: 'Session', position: 'insideBottom', offset: -2, fill: '#78716c', fontSize: 11 } }), _jsx(YAxis, { domain: [0, 100], tick: { fill: '#78716c', fontSize: 11 }, axisLine: false, tickLine: false }), _jsx(Tooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(Legend, { wrapperStyle: { fontSize: 12, color: '#78716c' } }), _jsx(ReferenceLine, { y: 40, stroke: "#10b981", strokeDasharray: "4 4", strokeWidth: 1, label: { value: 'Low', fill: '#10b981', fontSize: 10 } }), _jsx(ReferenceLine, { y: 70, stroke: "#ef4444", strokeDasharray: "4 4", strokeWidth: 1, label: { value: 'High', fill: '#ef4444', fontSize: 10 } }), _jsx(Area, { type: "monotone", dataKey: "stress_score", name: "Stress Score", stroke: "#f59e0b", strokeWidth: 2.5, fill: "url(#stressGrad)", dot: { fill: '#f59e0b', r: 3, strokeWidth: 0 }, activeDot: { r: 5, fill: '#d97706' } }), showCognitive && (_jsx(Area, { type: "monotone", dataKey: "cognitive_score", name: "Cognitive Score", stroke: "#10b981", strokeWidth: 2, fill: "url(#cogGrad)", dot: { fill: '#10b981', r: 3, strokeWidth: 0 }, activeDot: { r: 5, fill: '#059669' } }))] }) }) }));
}
